src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $slug = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $subname = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 5)]
    private ?string $postcode = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(type: Types::SMALLINT)]
    private ?int $status = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $small_image = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $image = null;

    #[ORM\ManyToMany(targetEntity: Category::class, inversedBy: 'posts')]
    private Collection $category;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: PostComment::class, orphanRemoval: true)]
    private Collection $comments;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phone = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $web = null;

    public function __construct()
    {
        $this->category = new ArrayCollection();
        $this->comments = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(?string $slug): static
    {
        $this->slug = $slug;

        return $this;
    }

    public function getSubname(): ?string
    {
        return $this->subname;
    }

    public function setSubname(?string $subname): static
    {
        $this->subname = $subname;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getStatus(): ?int
    {
        return $this->status;
    }

    public function setStatus(int $status): static
    {
        $this->status = $status;

        return $this;
    }

    public function getCategory(): Collection
    {
        return $this->category;
    }

    public function setCategory(Collection $category): static
    {
        $this->category = $category;

        return $this;
    }

    public function getSmallImage(): ?string
    {
        return $this->small_image;
    }

    public function setSmallImage(?string $small_image): static
    {
        $this->small_image = $small_image;

        return $this;
    }

    public function getImage(): ?string
    {
        return $this->image;
    }

    public function setImage(?string $image): static
    {
        $this->image = $image;

        return $this;
    }

    public function addCategory(Category $category): static
    {
        if (!$this->category->contains($category)) {
            $this->category->add($category);
        }

        return $this;
    }

    public function removeCategory(Category $category): static
    {
        $this->category->removeElement($category);

        return $this;
    }

    /**
     * @return Collection<int, PostComment>
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    public function addComment(PostComment $comment): static
    {
        if (!$this->comments->contains($comment)) {
            $this->comments->add($comment);
            $comment->setPost($this);
        }

        return $this;
    }

    public function removeComment(PostComment $comment): static
    {
        if ($this->comments->removeElement($comment)) {
            if ($comment->getPost() === $this) {
                $comment->setPost(null);
            }
        }

        return $this;
    }

    public function getPostcode(): ?string
    {
        return $this->postcode;
    }

    public function setPostcode(string $postcode): static
    {
        $this->postcode = $postcode;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(?string $email): static
    {
        $this->email = $email;

        return $this;
    }

    public function getPhone(): ?string
    {
        return $this->phone;
    }

    public function setPhone(?string $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getWeb(): ?string
    {
        return $this->web;
    }

    public function setWeb(?string $web): static
    {
        $this->web = $web;

        return $this;
    }

    public function getWebsiteName(): ?string
    {
        if (!$this->web) {
            return null;
        }

        $parsedUrl = parse_url($this->web);
        if (!$parsedUrl || !isset($parsedUrl['host'])) {
            return null;
        }

        return $parsedUrl['host'];
    }

    public function getPhoneLink(): ?string
    {
        $phoneNumber = $this->getPhone();

        if (!$phoneNumber) {
            return null;
        }

        $phoneNumber = preg_replace('/\D/', '', $phoneNumber);

        if (substr($phoneNumber, 0, 2) == "01") {
            $phoneNumber = "+49" . substr($phoneNumber, 1);
            return $phoneNumber;
        }

        if (substr($phoneNumber, 0, 2) == "49") {
            $phoneNumber = "+49" . substr($phoneNumber, 2);
            return $phoneNumber;
        }

        if (substr($phoneNumber, 0, 3) == "+49") {
            $phoneNumber = "+49" . substr($phoneNumber, 3);
            return $phoneNumber;
        }

        if (substr($phoneNumber, 0, 1) == "0") {
            $phoneNumber = "+49" . substr($phoneNumber, 1);
            return $phoneNumber;
        }

        return null;
    }

    public function getFormatedPhone(): ?string
    {
        $phoneNumber = $this->getPhone();

        if (!$phoneNumber) {
            return null;
        }
        
        $phoneNumber = preg_replace('/\D/', '', $phoneNumber);

        if (substr($phoneNumber, 0, 2) == "01") {
            $areaCode = substr($phoneNumber, 2, 3);
            $prefix = substr($phoneNumber, 5, 3);
            $lineNumber = substr($phoneNumber, 8);
            return "+49 ($areaCode) $prefix-$lineNumber";
        }

        if (substr($phoneNumber, 0, 2) == "49") {
            $areaCode = substr($phoneNumber, 2, 3);
            $prefix = substr($phoneNumber, 5, 3);
            $lineNumber = substr($phoneNumber, 8);
            return "+49 ($areaCode) $prefix-$lineNumber";
        }

        if (substr($phoneNumber, 0, 3) == "+49") {
            $areaCode = substr($phoneNumber, 3, 3);
            $prefix = substr($phoneNumber, 6, 3);
            $lineNumber = substr($phoneNumber, 9);
            return "+49 ($areaCode) $prefix-$lineNumber";
        }

        if (substr($phoneNumber, 0, 1) == "0") {
            $areaCode = substr($phoneNumber, 1, 4);
            $prefix = substr($phoneNumber, 5, 3);
            $lineNumber = substr($phoneNumber, 8);
            return "+49 ($areaCode) $prefix-$lineNumber";
        }

        return $this->getPhone();
    }

    public function getHeadline(): ?string
    {
        if ($this->getSubname()) {
            return $this->getSubname();
        }

        if ($this->getCategory()->count() > 0 && $this->getCity()) {
            return $this->getCategory()->first()->getName() . " in " . $this->getCity();
        }
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Entity\Post;
use App\Entity\PostComment;
use App\Form\PostCommentType;
use App\Form\PostType;
use App\Repository\CategoryRepository;
use App\Repository\PostCommentRepository;
use App\Repository\PostRepository;
use Knp\Component\Pager\Pagination\PaginationInterface;
use App\Service\FileUploader;
use Doctrine\ORM\EntityManagerInterface;
use Knp\Component\Pager\PaginatorInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\String\Slugger\AsciiSlugger;

#[Route('/post')]
class PostController extends AbstractController
{
    #[Route('/', name: 'app_post_index', methods: ['GET'])]
    public function index(
        Request $request,
        PaginatorInterface $paginator,
        PostRepository $postRepository,
        PostCommentRepository $commentRepository,
        EntityManagerInterface $entityManager
    ): Response
    {
        $entityManager->getFilters()
            ->enable('status_filter');
        
        $pagination = $paginator->paginate(
            $postRepository->findAllQuery(),
            $request->query->getInt('page', 1),
            10
        );

        $averageRatings = $this->getAverageRatingsForPagination($pagination, $commentRepository);

        return $this->render('post/index.html.twig', [
            'pagination' => $pagination,
            'averageRatings' => $averageRatings,
        ]);
    }

    #[Route('/new', name: 'app_post_new', methods: ['GET', 'POST'])]
    public function new(
        Request $request,
        EntityManagerInterface $entityManager,
        FileUploader $fileUploader,
        CategoryRepository $categoryRepository
    ): Response
    {
        $post = new Post();
        $form = $this->createForm(PostType::class, $post);

        if ($request->isMethod('POST')) {
            $data = $request->request->all();
            $tokenId = $form->getConfig()->getOption('csrf_token_id') ?? $form->getName();
            $tokenValue = $data['post']['_token'] ?? null;
            if ($tokenValue && $this->isCsrfTokenValid($tokenId, $tokenValue)
                && isset($data['post']['category']['autocomplete'])) {
                $slugger = new AsciiSlugger();
                $categoryName = $data['post']['category']['autocomplete'];
                $slug = $slugger->slug($categoryName);

                if (ctype_digit((string) $categoryName)) {
                    $category = $categoryRepository->find((int) $categoryName);
                } else {
                    $category = $categoryRepository->findOneBy(
                        ['slug' => $slug]
                    );
                }
                
                if (!$category) {
                    $category = new Category();
                    $category->setName($categoryName);
                    $category->setSlug($slug);

                    $entityManager->persist($category);
                    $entityManager->flush();
                }

                $data['post']['category']['autocomplete'] = $category->getId();
                $request->request->set('post', $data['post']);
            }
        }
        
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setStatus(0);
            $post->setSlug($this->slugifyPost($post));

            $category = $form->get('category')->getData();
            if ($category) {
                $post->addCategory($category);
            }

            $imageFile = $form->get('image')->getData();
            if ($imageFile) {
                $imageFileName = $fileUploader->upload($imageFile);
                $post->setImage($imageFileName);
            }

            $smallImage = $form->get('small_image')->getData();
            if ($smallImage) {
                $smallImageFileName = $fileUploader->upload($smallImage);
                $post->setSmallImage($smallImageFileName);
            }

            $entityManager->persist($post);
            $entityManager->flush();

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        $errors = $form->getErrors(true);

        return $this->render('post/new.html.twig', [
            'post' => $post,
            'form' => $form,
            'errors' => $errors,
        ]);
    }

    #[Route('/{id}', name: 'app_post_show', methods: ['GET', 'POST'], requirements: ['id' => '\d+'])]
    public function show(
        Request $request,
        Post $post
    ): Response
    {
        return $this->redirectToRoute('app_post_show_slug', [
            'id' => $post->getId(),
            'slug' => $this->slugifyPost($post),
        ], Response::HTTP_MOVED_PERMANENTLY);
    }

    #[Route('/{id}-{slug}', name: 'app_post_show_slug', methods: ['GET', 'POST'], requirements: ['id' => '\d+'])]
    public function showSlug(
        Request $request,
        Post $post,
        string $slug,
        EntityManagerInterface $entityManager,
        PostCommentRepository $commentRepository
    ): Response
    {
        $expectedSlug = $this->slugifyPost($post);
        if ($slug !== $expectedSlug) {
            return $this->redirectToRoute('app_post_show_slug', [
                'id' => $post->getId(),
                'slug' => $expectedSlug,
            ], Response::HTTP_MOVED_PERMANENTLY);
        }

        $comment = new PostComment();
        $commentForm = $this->createForm(PostCommentType::class, $comment);
        $commentForm->handleRequest($request);

        if ($commentForm->isSubmitted() && $commentForm->isValid()) {
            $comment->setPost($post);
            $comment->setIsApproved(false);
            $comment->setCreatedAt(new \DateTimeImmutable());

            $entityManager->persist($comment);
            $entityManager->flush();

            $this->addFlash('success', 'Vielen Dank! Ваш комментарий будет опубликован после проверки.');

            return $this->redirectToRoute('app_post_show_slug', [
                'id' => $post->getId(),
                'slug' => $expectedSlug,
            ]);
        }

        $approvedComments = $commentRepository->findApprovedForPost($post);

        return $this->render('post/show.html.twig', [
            'post' => $post,
            'commentForm' => $commentForm,
            'comments' => $approvedComments,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_post_edit', methods: ['GET', 'POST'])]
    public function edit(
        Request $request,
        Post $post,
        EntityManagerInterface $entityManager,
        FileUploader $fileUploader
    ): Response
    {
        $form = $this->createForm(PostType::class, $post);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $post->setSlug($this->slugifyPost($post));
            $imageFile = $form->get('image')->getData();
            if ($imageFile) {
                $imageFileName = $fileUploader->upload($imageFile);
                $post->setImage($imageFileName);
            }

            $smallImage = $form->get('small_image')->getData();
            if ($smallImage) {
                $smallImageFileName = $fileUploader->upload($smallImage);
                $post->setSmallImage($smallImageFileName);
            }

            $entityManager->flush();

            return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('post/edit.html.twig', [
            'post' => $post,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_post_delete', methods: ['POST'])]
    public function delete(Request $request, Post $post, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$post->getId(), $request->request->get('_token'))) {
            $entityManager->remove($post);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_post_index', [], Response::HTTP_SEE_OTHER);
    }

    private function slugifyPost(Post $post): string
    {
        $slugger = new AsciiSlugger();
        return strtolower((string) $slugger->slug((string) $post->getName()));
    }

    /**
     * @param PaginationInterface<Post> $pagination
     * @return array<int, array{average: float, count: int}>
     */
    private function getAverageRatingsForPagination(PaginationInterface $pagination, PostCommentRepository $commentRepository): array
    {
        $items = $pagination->getItems();
        if (!is_array($items)) {
            return [];
        }
        $ids = array_map(fn (Post $post) => $post->getId(), $items);
        return $commentRepository->getAverageRatingsForPosts($ids);
    }
}

templates/post/_contact.html.twig
{% if post.phone %}
    <div class="row">
        <div class="col-auto">
            <i class="bi bi-telephone text-accent"></i>
        </div>
        <div class="col">
            {% if post.phoneLink %}
                <a href="tel:{{post.phoneLink}}">{{post.formatedPhone}}</a>
            {% else %}
                {{post.formatedPhone}}
            {% endif %}
        </div>
    </div>
{% endif %}
{% if post.email %}
    <div class="row">
        <div class="col-auto">
            <i class="bi bi-envelope text-accent"></i>
        </div>
        <div class="col">
            <a href="mailto:{{post.email}}">{{post.email}}</a>
        </div>
    </div>
{% endif %}
{% if post.web %}
    <div class="row">
        <div class="col-auto">
            <i class="bi bi-browser-safari text-accent"></i>
        </div>
        <div class="col">
            <a href="{{post.web}}" target="_blank">{{post.websiteName}}</a>
        </div>
    </div>
{% endif %}

templates/post/_delete_form.html.twig
<form method="post" action="{{ path('app_post_delete', {'id': post.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ post.id) }}">
    <button class="btn">Delete</button>
</form>

templates/post/_form.html.twig
{{ form_start(form) }}
    <div class="row g-0">
        <div class="col-lg-5 quote-bg" style="background-image: url({{ asset('images/form-banner.jpg') }});"></div>
        <div class="col-lg-7 php-email-form">
            <div class="mb-5">
                <h3>Новая фирма</h3>
                <p>Здесь вы можете добавить информацию о вашей фирме или предложить свои услуги как специалист.</p>
                <p>Пожалуйста, заполните следующую форму с вашими данными, чтобы мы могли представить вашу фирму или профиль специалиста на нашем портале.</p>
            </div>
            <div class="form-errors">
                {{ form_errors(form) }}
            </div>

            <div class="row">
                <div class="col-md-12">
                    {{ form_row(form.name) }}
                    {{ form_row(form.category) }}
                </div>
            </div>
        </div>
    </div>

    <div class="php-email-form mt-4">
        <div class="row">
            <div class="mb-3">
                <h3>Контактные данные</h3>
            </div>
            <div class="col-lg-6 address">
                <div>
                    {{ form_row(form.address) }}
                </div>
                <div class="row">
                    <div class="col-4">
                        {{ form_row(form.postcode) }}
                    </div>
                    <div class="col-8">
                        {{ form_row(form.city) }}
                    </div>
                </div>
            </div>
            <div class="col-lg-6 contact">
                {{ form_row(form.email) }}
                {{ form_row(form.phone) }}
                {{ form_row(form.web) }}
            </div>
        </div>
        
        <div
            data-controller="colapse"
            data-colapse-more-text-value="Показать дополнителную информацию"
            data-colapse-less-text-value="Скрыть дополнителную информацию"
            {% if errors|length > 0 %}
                data-colapse-open-value="1"
            {% endif %}
        >
            <a class="link-info link-underline-info link-offset-2" data-action="colapse#toggle">
                Показать дополнителную информацию
            </a>
            <div class="py-5" data-colapse-target="content" hidden>
                <div class="row">
                    <div class="col-lg-6">
                        {{ form_row(form.description) }}
                    </div>
                    <div class="col-lg-6">
                        {{ form_row(form.image) }}
                        {{ form_row(form.small_image) }}
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="php-email-form">
        <div class="row">
            <div class="col-md-6">
                {# <div class="loading">Loading</div> #}
                <div class="error-message"></div>
                <div class="sent-message">Your quote request has been sent successfully. Thank you!</div>
                <button class="btn btn-primary">{{ button_label|default('Добавить фирму') }}</button>
            </div>
        </div>
    </div>
{{ form_end(form) }}

templates/post/_list.html.twig
<div class="posts py-5">
    <div class="row">
        {% for post in posts %}
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="row g-0">
                    {% if post.smallImage %}
                        <div class="col-md-4">
                            <img class="img-fluid" src="{{asset('uploads/posts/' ~ post.smallImage)}}" alt="{{post.name}}">
                        </div>
                    <div class="col-md-8">
                    {% else %}
                        <div class="col-md-12">
                    {% endif %}
                        <div class="card-body">
                            <a href="{{ post.slug ? path('app_post_show_slug', {'id': post.id, 'slug': post.slug}) : path('app_post_show', {'id': post.id}) }}" class="card-body-cover" aria-label="{{ post.name }}"></a>
                            <h5 class="card-title">{{ post.name }}</h5>
                            {% set rating = averageRatings[post.id] is defined ? averageRatings[post.id] : null %}
                            {% if rating and rating.count > 0 %}
                                <div class="post-list-stars text-accent mb-2" aria-label="Рейтинг: {{ rating.average|number_format(1) }} из 5 ({{ rating.count }} отзывов)">
                                    {% for i in 1..5 %}
                                        {% if rating.average >= i %}
                                            <i class="bi bi-star-fill"></i>
                                        {% elseif rating.average >= i - 0.5 %}
                                            <i class="bi bi-star-half"></i>
                                        {% else %}
                                            <i class="bi bi-star"></i>
                                        {% endif %}
                                    {% endfor %}
                                    <span class="text-muted small ms-1">({{ rating.count }})</span>
                                </div>
                            {% endif %}
                            <div class="categories mb-3">
                                {% for category in post.category %}
                                    <a href="{{ path('app_category_show', {'slug': category.slug}) }}" class="category-link text-accent">{{ category.name }}</a>{% if not loop.last %} · {% endif %}
                                {% endfor %}
                            </div>
                            <div class="address mb-1 text-small">
                                 {{post.address}} · {{post.postcode}} {{post.city}}
                            </div>
                            <div class="contact mb-2 text-small">
                                {% if post.phone %}
                                    <i class="bi bi-telephone text-accent"></i>
                                    <span>
                                        {% if post.phoneLink %}
                                            <a href="tel:{{post.phoneLink}}">{{post.formatedPhone}}</a>
                                        {% else %}
                                            {{post.formatedPhone}}
                                        {% endif %}
                                    </span>
                                {% endif %}
                            </div>
                            <div class="btn-wrap">
                                <a href="{{ post.slug ? path('app_post_show_slug', {'id': post.id, 'slug': post.slug}) : path('app_post_show', {'id': post.id}) }}" class="btn btn-accent btn-sm btn-cta mt-3">посмотреть<i class="bi bi-chevron-right ms-1"></i></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        {% else %}
            <div>
                no records found
            </div>
        {% endfor %}
    </div>
</div>

templates/post/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Post{% endblock %}

{% block body %}
    <h1>Edit Post</h1>

    {{ include('post/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_post_index') }}">back to list</a>

    {{ include('post/_delete_form.html.twig') }}
{% endblock %}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Post index{% endblock %}

{% block body %}
    <div class="container aos-init aos-animate" data-aos="fade-up">
        <h1>Post index</h1>

        {% include 'post/_list.html.twig' with {'posts': pagination, 'averageRatings': averageRatings|default({})} %}
        <div class="navigation">
            {{ knp_pagination_render(pagination) }}
        </div>
    </div>
{% endblock %}

templates/post/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Добавить фирму{% endblock %}
{% block headline %}Добавить новую фирму или специалиста{% endblock %}
{% block description %}{% endblock %}
{% block breadcrumb %}Добавить фирму{% endblock %}

{% block body %}
    <div id="new-post-form" class="container py-5" data-aos="fade-up">
        {{ include('post/_form.html.twig') }}
    </div>
{% endblock %}